# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Configuration for npm (Nuxt front-end)
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'

  # Configuration for Dockerfile
  - package-ecosystem: 'docker'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'

  # Configuration for DockerCompose
  - package-ecosystem: 'composer'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'

  # Configuration for cargo (Tauri Rust back-end)
  - package-ecosystem: 'cargo'
    directory: '/src-tauri' # Emplacement des manifests de paquets (Cargo.toml)
    schedule:
      interval: 'daily'

  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows' # Chemin vers le répertoire contenant vos fichiers de workflow GitHub Actions
    schedule:
      interval: 'daily'
