apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: staging-seatyrants-website-frontend-hpa
  namespace: staging-seatyrants-website-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: staging-seatyrants-website-frontend-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
