name: tests_deploy-release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  tests_deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js to latest version LTS and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      # Contrainte de devoir faire ça pour generer le dossier .nuxt avant de pouvoir faire le lint:vue
      - name: Build Project for Staging
        run: npm run build:static:prod

      - name: Install dependencies for project
        run: npm install

      - name: Lint TypeScript and ESLint for project
        run: npm run lint:eslint && npm run lint:ts

      - name: Run Unit Tests and E2E Tests
        run: npm run test:unit:staging-prod # && npm run test:e2e

      - name: Deploy PR (main) for new Release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          target-branch: main
          config-file: 'release-please-config.json'
          token: ${{ secrets.GITHUB_TOKEN }}
